# -*- coding: utf-8 -*-
"""Assignment1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ae6PHJfEwCvDakVoCnmY-hwaE9JVVHHf
"""

import warnings
warnings.filterwarnings('ignore')

import numpy as np
import pandas as pd

import tensorflow.keras as kb
from tensorflow.keras import backend
import tensorflow as tf
from sklearn.preprocessing import LabelBinarizer
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers.experimental import preprocessing

import PIL
from tensorflow.keras.utils import load_img
from tensorflow.keras.utils import img_to_array
from keras.applications.imagenet_utils import decode_predictions
import matplotlib.pyplot as plt
# from keras.applications.resnet50 import ResNet50
# from keras.applications import resnet50
import model_creator
import jpeg_cleaner
import image_tester
import training_plot
    

def run(condition):
    if condition:
        epochs = 15

        image_paths = ['./CarBodyStyles/Buggy', './CarBodyStyles/Convertible', './CarBodyStyles/Coupe',
                    './CarBodyStyles/Hatchback','./CarBodyStyles/Limousine','./CarBodyStyles/Minivan',
                    './CarBodyStyles/Sedan']

        # found invalid files during training, so this removes them
        jpeg_cleaner.jpeg_remover(directory_path = "./CarBodyStyles", subdirectories = image_paths)

        history = model_creator.model_creator(epochs = epochs)

        training_plot.plot(history, epochs) # plotting out the training process and associated performance metrics


    """Testing on specific images"""

    loaded_model = tf.keras.models.load_model("./model_directory")
    classes = model_creator.get_class_names(directory = "./CarBodyStyles")


    test_image_paths_and_labels = {"./TestingImages/718_spyder_gentianblue.png":"convertible", "./TestingImages/2017-volkswagen-golf-gti-sport-review.jpg":"hatchback",
                                "./TestingImages/Buggy.jpg":"buggy", "./TestingImages/Limo.jpg":"limo", "./TestingImages/M2Comp.png":"coupe",
                                "./TestingImages/Sienna.jpg":"minivan", "./TestingImages/white_sedan.jpg":"sedan"}

    image_tester.test_multiple_images(test_image_paths_and_labels, loaded_model, classes)
    
    